apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-2
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/manukoli1986/gitops-2.git
    targetRevision: HEAD
    path: myapp
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.pullPolicy
          value: Always
        - name: image.repository
          value: manukoli1986/myapp
        - name: service.type
          value: LoadBalancer
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true